#!/bin/bash

while [[ $# > 0 ]]
do
    key="$1"

    case $key in
    "node")
        cat scontrol_show_node.txt ;;
    "job")
        cat scontrol_show_job.txt ;;
    *)
        ;;
    esac
    shift
done

